export const LogEventType = {
  // Payment events
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_MANUAL_RECORDED: "PAYMENT_MANUAL_RECORDED",

  // Email events
  EMAIL_SENT: "EMAIL_SENT",
  EMAIL_DELIVERED: "EMAIL_DELIVERED",
  EMAIL_BOUNCED: "EMAIL_BOUNCED",
  EMAIL_OPENED: "EMAIL_OPENED",

  // Auth events
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_PASSWORD_RESET: "AUTH_PASSWORD_RESET",
  AUTH_EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",

  // Invoice events
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_SENT: "INVOICE_SENT",
  INVOICE_VIEWED: "INVOICE_VIEWED",
  INVOICE_PAID: "INVOICE_PAID",
  INVOICE_OVERDUE: "INVOICE_OVERDUE",
  INVOICE_CANCELED: "INVOICE_CANCELED",
  INVOICE_REFUNDED: "INVOICE_REFUNDED",

  // Membership events
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",

  // Organization events
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_DELETED: "ORG_DELETED",

  // Admin events
  ADMIN_TIER_CHANGED: "ADMIN_TIER_CHANGED",
  ADMIN_USER_SUSPENDED: "ADMIN_USER_SUSPENDED",
  ADMIN_USER_REINSTATED: "ADMIN_USER_REINSTATED",
} as const;

export type LogEventType =
  (typeof LogEventType)[keyof typeof LogEventType];
